---
- name: harp - installing dependencies
  hosts: all
  sudo: yes

  roles:
    - Ansibles.nodejs

- name: harp - build sample webapp
  hosts: all
  sudo: yes

  vars:
    nodejs_install_method: "source"
    nodejs_version: "0.10.26"
    harp_build_git_repo: 'https://github.com/cauliturtle/harp-simple-blog'
    harp_build_site_name: 'harp-simple-blog'

  vars_files:
    - 'defaults/main.yml'

  tasks:
    - include: 'tasks/main.yml'
