---
- name: harp - installing dependencies
  hosts: all
  sudo: yes

  vars:
    harp_build_git_repo: 'https://github.com/cauliturtle/harp-simple-blog'
    harp_build_site_name: 'harp-simple-blog'

  roles:
    - .
