---
- name: harp - testing with Vagrant
  hosts: all
  sudo: yes

  vars:
    nodejs_install_method: "source"
    nodejs_version: "0.10.26"
    harp_build_git_repo: 'https://github.com/cauliturtle/harp-simple-blog'
    harp_build_site_name: 'harp-simple-blog'

  roles:
    - Ansibles.nodejs
    - .
