---
- name: deploy - install apache
  apt: pkg=apache2 update_cache=yes cache_valid_time=3600 state=present
  notify: apache - enable

- name: deploy - create directory for apache sites confs
  file: dest={{ harp_deploy_conf_dir }} state=directory owner=root group=root mode=0755

- name: deploy - make sites directories
  file: dest={{ harp_deploy_site.path }} recurse=yes state=directory owner=root group=root mode=0755

- name: deploy - set main conf
  template: src=harp.j2 dest=/etc/apache2/sites-available/harp
  notify: apache - restart

- name: deploy - set sites confs
  template: src=site.j2 dest={{ harp_deploy_conf_dir }}/{{ harp_deploy_site.name }}.conf
  notify: apache - restart

- name: deploy - enable site conf in apache
  file: src=/etc/apache2/sites-available/harp dest=/etc/apache2/sites-enabled/harp state=link
  notify: apache - restart
